name: Cypress Tests using Cypress Docker Image
# thanks to @TimeForANinjas patience to help me with this, it finally works
# i am released from this hell that is called programming github actions

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: pre-build docker compose images
        run: docker compose -f docker-compose.testing.yml build

      - name: run cypress
        run: docker compose -f docker-compose.testing.yml up --exit-code-from cypress

      #- name: upload artifacts
      #  if: always()
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: cypress-for-branch-${{ github.ref_name }}
      #    path: |
      #      testing/cypress/screenshots
      #      testing/cypress/videos
